const source = 'src';
const dist = 'lib';

function getExposesByFiles(files) {
  return files.reduce((result, file) => {
    result[`./${dist}/${file}`] = `./${source}/${file}`;
    return result;
  }, {});
}

module.exports = {
  hzeroMS: {
    exposes: {
      ...getExposesByFiles([
        'assets/icon_upload.svg',
        'assets/icon_excel.svg',
        'assets/icon_page_wrong.svg',
        'assets/logo-placeholder.png',
        'assets/no-message.png',
        'assets/reg-logo.png',
        'components/Authorized/WrapAuthorized',
        'components/CacheComponent',
        'components/Checkbox',
        'components/CodeMirror',
        'components/CommonImport/Route',
        'components/Compose/ComposeForm',
        'components/Compose/ComposeTable',
        'components/CountDown',
        'components/CustomTable',
        'components/DynamicComponent/config',
        'components/DynamicComponent/DynamicForm',
        'components/DynamicComponent/DynamicModal',
        'components/DynamicComponent/DynamicPage',
        'components/DynamicComponent/DynamicTable',
        'components/DynamicComponent/DynamicTable/utils',
        'components/DynamicComponent/DynamicToolbar',
        'components/EditTable',
        'components/ExcelExport',
        'components/ExcelExportPro',
        'components/Exception',
        'components/EmbedPage',
        'components/FileChunkUploader',
        'components/Icons',
        'components/IconsPicker',
        'components/Import',
        'components/LowCodeProvider',
        'components/Lov',
        'components/Lov/index.less',
        'components/Modal/ModalContainer',
        'components/Modal/ModalForm',
        'components/Modal/SideBar',
        'components/NProgress/LoadingBar',
        'components/OnlineWord',
        'components/OnlyOfficeEditor',
        'components/Page',
        'components/Permission',
        'components/PermissionButton',
        'components/Permission/PermissionProvider',
        'components/Permission/Status',
        'components/RichTextEditor',
        'components/SearchPage',
        'components/Switch',
        'components/TagSelect',
        'components/TinymceEditor',
        'components/TLEditor',
        'components/UedTheme',
        'components/Upload',
        'components/Upload/UploadButton',
        'components/ValueList',
        'components/VirtualTable',
        'components/OptionInput',
        'customize/cards',
        'customize/customizeTracking',
        'customize/himp',
        'customize/hfle',
        'customize/hmsg',
        'customize/hpfm',
        'customize/traceLog',
        'customize/workflowApproveForm',
        'layouts/Layout',
        'layouts/PubLayout',
        'layouts/PublicLayout',
        'layouts/MiniLayout',
        'layouts/NewLayout/utils',
        'models/global',
        'models/user',
        'models/workplace',
        'router',
        'routes',
        'routes/Dashboard/Workplace/CardsSetting',
        'routes/Dashboard/Workplace/index.less',
        'services/api',
        'services/api/file',
        'services/api/language',
        'utils/browser',
        'utils/c7nUiConfig',
        'utils/c7n-ued-polyfill.important.less',
        'utils/config',
        'utils/constants',
        'utils/customize',
        'utils/customize/helpers',
        'utils/getConvertRouter',
        'utils/iocUtils',
        'utils/iocUtils/helpers',
        'utils/intl',
        'utils/intl/formatterCollections',
        'utils/intl/LocaleProviderAsync',
        'utils/menuTab',
        'utils/notification',
        'utils/regExp',
        'utils/remote',
        'utils/renderer',
        'utils/request',
        'utils/router',
        'utils/utils',
        'utils/utils/user',
        'utils/withProps',
        'utils/webSoket',
        'index.less',
      ]),
    },
    splitChunks: {
      cacheGroups: {
        common: {
          minChunks: 2,
          priority: -20,
          chunks: 'initial',
          name: 'chunk-common',
          reuseExistingChunk: true,
        },
        vendors: {
          test: /[\\/]node_modules[\\/](?!moment[\\/]locale)/,
          priority: -10,
          name: 'chunk-vendors',
          chunks: 'async',
        },
        moment: {
          test: /[\\/]node_modules[\\/]moment[\\/]/,
          priority: 100,
          name: 'moment',
        },
        tinymce: {
          test: /[\\/]node_modules[\\/]tinymce[\\/]tinymce.min.js/,
          priority: 100,
          name: 'tinymce',
        },
        'react-intl-universal': {
          test: /[\\/]node_modules[\\/]react-intl-universal[\\/]/,
          priority: 100,
          name: 'react-intl-universal',
        },
        'intl': {
          test: /[\\/]node_modules[\\/]intl[\\/]/,
          priority: 100,
          name: 'intl',
        },
        'crypto-js': {
          test: /[\\/]node_modules[\\/]crypto-js[\\/]/,
          priority: 100,
          name: 'crypto-js',
        },
        'webuploader': {
          test: /[\\/]node_modules[\\/]webuploader[\\/]/,
          priority: 100,
          name: 'webuploader',
        },
        'elliptic': {
          test: /[\\/]node_modules[\\/]elliptic[\\/]/,
          priority: 100,
          name: 'elliptic',
        },
        'mobx': {
          test: /[\\/]node_modules[\\/]mobx[\\/]/,
          priority: 100,
          name: 'mobx',
        },
        'html-to-react': {
          test: /[\\/]node_modules[\\/]html-to-react[\\/]/,
          priority: 100,
          name: 'html-to-react',
        },
        'styled-components': {
          test: /[\\/]node_modules[\\/]styled-components[\\/]/,
          priority: 100,
          name: 'styled-components',
        },
        'dva': {
          test: /[\\/]node_modules[\\/]dva[\\/]/,
          priority: 100,
          name: 'dva',
        },
        'dva-core': {
          test: /[\\/]node_modules[\\/]dva-core[\\/]/,
          priority: 100,
          name: 'dva-core',
        },
        'react-draggable': {
          test: /[\\/]node_modules[\\/]react-draggable[\\/]/,
          priority: 100,
          name: 'react-draggable',
        },
        'react-viewer': {
          test: /[\\/]node_modules[\\/]react-viewer[\\/]/,
          priority: 100,
          name: 'react-viewer',
        },
        'react-grid-layout': {
          test: /[\\/]node_modules[\\/]react-grid-layout[\\/]/,
          priority: 100,
          name: 'react-grid-layout',
        },
        'bn': {
          test: /[\\/]node_modules[\\/]bn.js[\\/]/,
          priority: 100,
          name: 'bn',
        },
        'jsencrypt': {
          test: /[\\/]node_modules[\\/]jsencrypt[\\/]/,
          priority: 100,
          name: 'jsencrypt',
        },
        'entities': {
          test: /[\\/]node_modules[\\/]entities[\\/]/,
          priority: 100,
          name: 'entities',
        },
        'tinymce-themes': {
          test: /[\\/]node_modules[\\/]tinymce[\\/]themes[\\/]/,
          priority: 100,
          name: 'tinymce-themes',
        },
        'tinymce-plugins': {
          test: /[\\/]node_modules[\\/]tinymce[\\/]plugins[\\/]/,
          priority: 100,
          name: 'tinymce-plugins',
        },
        'react-dom': {
          test: /[\\/]node_modules[\\/]react-dom[\\/]/,
          priority: 100,
          name: 'react-dom',
        },
        'react-router': {
          test: /[\\/]node_modules[\\/]react-router[\\/]/,
          priority: 100,
          name: 'react-router',
        },
        'jquery': {
          test: /[\\/]node_modules[\\/]jquery[\\/]/,
          priority: 100,
          name: 'jquery',
        },
        'lodash-decorators': {
          test: /[\\/]node_modules[\\/]lodash-decorators[\\/]/,
          priority: 100,
          name: 'lodash-decorators',
        },
        'lodash': {
          test: /[\\/]node_modules[\\/]lodash[\\/](?!lodash.js)/,
          priority: 100,
          name: 'lodash',
        },
        'lodash-all': {
          test: /[\\/]node_modules[\\/]lodash[\\/]lodash.js/,
          priority: 100,
          name: 'lodash-all',
        },
        'layout-components': {
          test: /hzero-front[\\/]src[\\/]layouts[\\/]components[\\/]/,
          priority: 100,
          name: 'layout-components',
        },
        'default-layout': {
          test: /hzero-front[\\/]src[\\/]layouts[\\/]DefaultLayout[\\/]/,
          priority: 100,
          name: 'default-layout',
        },
        'common': {
          test: /hzero-front[\\/]src[\\/]/,
          priority: 100,
          name: 'common',
        },
        'assets': {
          test: /hzero-front[\\/]src[\\/]assets[\\/]/,
          priority: 110,
          name: 'assets',
        },
        'layout': {
          test: /[\\/]layouts[\\/]Layout/,
          priority: 110,
          name: 'layout',
        },
        'common-layout': {
          test: /[\\/]layouts[\\/]CommonLayout[\\/]/,
          priority: 120,
          name: 'common-layout',
        },
        'mini-layout': {
          test: /[\\/]layouts[\\/]MiniLayout[\\/]/,
          priority: 120,
          name: 'mini-layout',
        },
        'new-layout': {
          test: /[\\/]layouts[\\/]NewLayout[\\/]/,
          priority: 120,
          name: 'new-layout',
        },
        'side-layout': {
          test: /[\\/]layouts[\\/]SideLayout[\\/]/,
          priority: 120,
          name: 'side-layout',
        },
        'side-line-layout': {
          test: /[\\/]layouts[\\/]SideLineLayout[\\/]/,
          priority: 120,
          name: 'side-line-layout',
        },
        'top-layout': {
          test: /[\\/]layouts[\\/]TopLayout[\\/]/,
          priority: 120,
          name: 'top-layout',
        },
        'pub-layout': {
          test: /[\\/]layouts[\\/]PubLayout/,
          priority: 120,
          name: 'pub-layout',
        },
        'import-components': {
          test: /src[\\/]components[\\/]Import[\\/]/,
          priority: 110,
          name: 'import-components',
        },
        'dynamic-components': {
          test: /src[\\/]components[\\/]DynamicComponent[\\/]/,
          priority: 110,
          name: 'dynamic-components',
        },
        'layouts-components': {
          test: /src[\\/]layouts[\\/]components[\\/]/,
          priority: 100,
          name: 'layouts-components',
        },
      },
    },
  },
};
