export enum EcSignStatus {
  UNSIGNED = 'UNSIGNED',
  REJECTED = 'REJECTED',
  SIGNING = 'SIGNING',
  SIGNED = 'SIGNED',
  ACTIVATED = 'ACTIVATED',
  TERMINATED = 'TERMINATED',
  OFFLINE_ACTIVE = "OFFLINE_ACTIVE"
}
