module.exports = [
  {
    path: '/hpfm/api-customize',
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/api-customize/list',
        FilterSupplier: true,
        component: () => import('../routes/ApiIndividuation'),
      },
      {
        path: '/hpfm/api-customize/:type/:id',
        FilterSupplier: true,
        component: () => import('../routes/ApiIndividuation/Detail'),
      },
    ],
  },
  {
    path: '/hpfm/card-manage',
    FilterSupplier: true,
    component: () => import('../routes/CardManage'),
    models: [() => import('../models/cardManage')],
  },
  {
    path: '/private/hpfm/card-manage',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/CardManage'),
    models: [() => import('../models/cardManage')],
  },
  {
    path: '/hpfm/excel-async-export',
    FilterSupplier: true,
    component: () => import('../routes/ExcelAsyncExport'),
    models: [() => import('../models/excelAsyncExport')],
  },
  {
    path: '/hpfm/cost-center',
    FilterSupplier: true,
    component: () => import('../routes/CostCenter'),
    models: [() => import('../models/costCenter')],
  },
  {
    path: '/private/hpfm/excel-async-export',
    key: '/private/hpfm/excel-async-export',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/ExcelAsyncExport'),
    models: [() => import('../models/excelAsyncExport')],
  },
  {
    path: '/hpfm/code-rule',
    models: [() => import('../models/codeRule')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/code-rule/list',
        FilterSupplier: true,
        component: () => import('../routes/CodeRule/CodeRuleList'),
        models: [() => import('../models/codeRule')],
      },
      {
        path: '/hpfm/code-rule/dist/:id',
        FilterSupplier: true,
        component: () => import('../routes/CodeRule/CodeRuleDist'),
        models: [() => import('../models/codeRule')],
      },
    ],
  },
  {
    path: '/private/hpfm/code-rule',
    authorized: true,
    models: [() => import('../models/codeRule')],
    FilterSupplier: true,
    components: [
      {
        path: '/private/hpfm/code-rule/list',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/CodeRule/CodeRuleList'),
        models: [() => import('../models/codeRule')],
      },
      {
        path: '/private/hpfm/code-rule/dist/:id',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/CodeRule/CodeRuleDist'),
        models: [() => import('../models/codeRule')],
      },
    ],
  },
  {
    path: '/hpfm/code-rule-org',
    models: [() => import('../models/codeRuleOrg')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/code-rule-org/list',
        FilterSupplier: true,
        component: () => import('../routes/CodeRuleOrg/CodeRuleList'),
        models: [() => import('../models/codeRuleOrg')],
      },
      {
        path: '/hpfm/code-rule-org/dist/:id',
        FilterSupplier: true,
        component: () => import('../routes/CodeRuleOrg/CodeRuleDist'),
        models: [() => import('../models/codeRuleOrg')],
      },
    ],
  },
  {
    path: '/private/hpfm/code-rule-org',
    authorized: true,
    models: [() => import('../models/codeRuleOrg')],
    FilterSupplier: true,
    components: [
      {
        path: '/private/hpfm/code-rule-org/list',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/CodeRuleOrg/CodeRuleList'),
        models: [() => import('../models/codeRuleOrg')],
      },
      {
        path: '/private/hpfm/code-rule-org/dist/:id',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/CodeRuleOrg/CodeRuleDist'),
        models: [() => import('../models/codeRuleOrg')],
      },
    ],
  },
  {
    path: '/pub/hpfm/code-rule-org/dist/:id',
    FilterSupplier: true,
    component: () => import('../routes/CodeRuleOrg/CodeRuleDist'),
    authorized: true,
    key: '/pub/hpfm/code-rule-org/dist/:id',
    models: [() => import('../models/codeRuleOrg')],
  },
  {
    path: '/hpfm/config',
    FilterSupplier: true,
    component: () => import('../routes/Config'),
    models: [() => import('../models/config')],
  },
  {
    path: '/private/hpfm/config',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/Config'),
    models: [() => import('../models/config')],
  },
  {
    // 数据源驱动
    path: '/hpfm/data-source-driver',
    FilterSupplier: true,
    component: () => import('../routes/DatasourceDriver'),
    models: [() => import('../models/datasourceDriver')],
  },
  // 系统管理--模板维护
  {
    path: '/hpfm/templates',
    FilterSupplier: true,
    component: () => import('../routes/Templates'),
    models: [() => import('../models/hpfmTemplate')],
  },
  // 系统管理--模板管理
  // {
  //   path: '/hpfm/template-configs',
  //   FilterSupplier: true,
  //   component: () => import('../routes/TemplateConfigs'),
  //   models: [() => import('../models/templateConfigs')],
  //   key: '/hpfm/template-configs',
  //   authorized: true,
  //   title: '系统管理--模板管理',
  // },
  // 表单动态配置
  {
    path: '/hpfm/dynamic-form',
    models: [],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/dynamic-form/list',
        models: [() => import('../models/dynamicForm/header')],
        FilterSupplier: true,
        component: () => import('../routes/DynamicForm/Header/index'),
      },
      {
        path: '/hpfm/dynamic-form/detail/:formHeaderId',
        models: [
          () => import('../models/dynamicForm/header'),
          () => import('../models/dynamicForm/line'),
        ],
        FilterSupplier: true,
        component: () => import('../routes/DynamicForm/Line/index'),
      },
    ],
  },
  // 系统管理-服务器集群管理
  {
    path: '/hpfm/server-cluster',
    FilterSupplier: true,
    component: () => import('../routes/ServerCluster'),
    models: [() => import('../models/serverCluster')],
  },
  {
    path: '/private/hpfm/server-cluster',
    key: '/private/hpfm/server-cluster',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/ServerCluster'),
    models: [() => import('../models/serverCluster')],
  },
  {
    path: '/hpfm/server-define',
    FilterSupplier: true,
    component: () => import('../routes/ServerDefine'),
    models: [() => import('../models/serverDefine')],
  },
  {
    path: '/private/hpfm/server-define',
    key: '/private/hpfm/server-define',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/ServerDefine'),
    models: [() => import('../models/serverDefine')],
  },
  {
    path: '/hpfm/dashboard-clause',
    models: [() => import('../models/dashboardClause')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/dashboard-clause/list',
        FilterSupplier: true,
        component: () => import('../routes/DashboardClause'),
        models: [() => import('../models/dashboardClause')],
      },
      {
        path: '/hpfm/dashboard-clause/create',
        FilterSupplier: true,
        component: () => import('../routes/DashboardClause/Detail'),
        models: [() => import('../models/dashboardClause')],
      },
      {
        path: '/hpfm/dashboard-clause/detail/:clauseId',
        FilterSupplier: true,
        component: () => import('../routes/DashboardClause/Detail'),
        models: [() => import('../models/dashboardClause')],
      },
    ],
  },
  {
    path: '/private/hpfm/dashboard-clause',
    authorized: true,
    models: [() => import('../models/dashboardClause')],
    FilterSupplier: true,
    components: [
      {
        path: '/private/hpfm/dashboard-clause/list',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/DashboardClause'),
        models: [() => import('../models/dashboardClause')],
      },
      {
        path: '/private/hpfm/dashboard-clause/create',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/DashboardClause/Detail'),
        models: [() => import('../models/dashboardClause')],
      },
      {
        path: '/private/hpfm/dashboard-clause/detail/:clauseId',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/DashboardClause/Detail'),
        models: [() => import('../models/dashboardClause')],
      },
    ],
  },
  {
    path: '/hpfm/data-source',
    models: [() => import('../models/dataSource')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/data-source/list',
        FilterSupplier: true,
        component: () => import('../routes/DataSource'),
        models: [() => import('../models/dataSource')],
      },
      {
        path: '/hpfm/data-source/detail/:datasourceId',
        FilterSupplier: true,
        component: () => import('../routes/DataSource/Detail'),
        models: [() => import('../models/dataSource')],
      },
    ],
  },
  {
    path: '/hpfm/data-hierarchies',
    FilterSupplier: true,
    component: () => import('../routes/DataHierarchies'),
    models: [() => import('../models/dataHierarchies')],
  },
  {
    path: '/private/hpfm/data-hierarchies',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/DataHierarchies'),
    models: [() => import('../models/dataHierarchies')],
  },
  // {
  //   path: '/hpfm/event',
  //   models: [],
  //   FilterSupplier: true,
  //   components: [
  //     {
  //       path: '/hpfm/event/list',
  //       FilterSupplier: true,
  //       component: () => import('../routes/Event/EventList'),
  //       models: [() => import('../models/event')],
  //     },
  //     {
  //       path: '/hpfm/event/detail/:id',
  //       FilterSupplier: true,
  //       component: () => import('../routes/Event/EventDetail'),
  //       models: [() => import('../models/event')],
  //     },
  //     {
  //       path: '/hpfm/event/graph/:id',
  //       FilterSupplier: true,
  //       component: () => import('../routes/Event/Flow/FlowPage'),
  //       models: [() => import('../models/event')],
  //     },
  //     // {
  //     //   path: '/hpfm/event/message/:id',
  //     //   FilterSupplier: true,
  //     //   component: () => import('../routes/Event/EventMessage'),
  //     //   models: [() => import('../models/event')],
  //     // },
  //   ],
  // },
  {
    path: '/hpfm/financial-code',
    models: [],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/financial-code/list',
        FilterSupplier: true,
        component: () => import('../routes/FinancialCode'),
        models: [() => import('../models/financialCode')],
      },
    ],
  },
  {
    path: '/hpfm/hr/org',
    models: [() => import('../models/organization')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/hr/org/company',
        FilterSupplier: true,
        component: () => import('../routes/Organization'),
        models: [() => import('../models/organization')],
      },
      {
        path: '/hpfm/hr/org/department/:companyId',
        FilterSupplier: true,
        component: () => import('../routes/Department'),
        models: [() => import('../models/department')],
      },
      {
        path: '/hpfm/hr/org/company/:code',
        component: () => import('../routes/himp/CommentImport'),
        authorized: true,
        models: [],
        FilterSupplier: true,
      },
      {
        path: '/hpfm/hr/org/post/:unitId',
        FilterSupplier: true,
        component: () => import('../routes/Post'),
        models: [() => import('../models/post')],
      },
      {
        path: '/hpfm/hr/org/staff/:positionId',
        FilterSupplier: true,
        component: () => import('../routes/Staff'),
        models: [() => import('../models/staff')],
      },
    ],
  },
  {
    path: '/hpfm/org',
    models: [],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/org/list',
        FilterSupplier: true,
        component: () => import('../routes/NewOrganization'),
        models: [],
      },
    ],
  },
  {
    path: '/hpfm/hr/staff',
    models: [],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/hr/staff/list',
        FilterSupplier: true,
        component: () => import('../routes/Employee/List'),
        models: [() => import('../models/employee')],
      },
      {
        path: '/hpfm/hr/staff/detail/:employeeId/:employeeNum',
        FilterSupplier: true,
        component: () => import('../routes/Employee/Detail'),
        models: [() => import('../models/employee')],
      },
      {
        authorized: true,
        path: '/hpfm/hr/staff/data-import/:code',
        FilterSupplier: true,
        component: () => import('../routes/himp/CommentImport'),
        models: [],
      },
      {
        authorized: true,
        path: '/hpfm/hr/staff/sub-import/:code',
        component: () => import('../routes/himp/CommentImport'),
        models: [],
        FilterSupplier: true,
      },
    ],
  },
  {
    path: '/hpfm/languages',
    FilterSupplier: true,
    component: () => import('../routes/Languages'),
    models: [() => import('../models/languages')],
  },
  {
    path: '/hpfm/lov-view',
    models: [() => import('../models/lovSetting')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/lov-view/lov-view-list',
        FilterSupplier: true,
        component: () => import('../routes/Lov/LovSetting'),
        models: [() => import('../models/lovSetting')],
      },
      {
        path: '/hpfm/lov-view/detail/:id',
        FilterSupplier: true,
        component: () => import('../routes/Lov/Detail'),
        models: [() => import('../models/lovSetting')],
      },
    ],
  },
  {
    path: '/hpfm/mdm/bank',
    FilterSupplier: true,
    component: () => import('../routes/Bank'),
    models: [() => import('../models/bank')],
  },
  {
    path: '/hpfm/mdm/calendar',
    models: [],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/mdm/calendar/list',
        FilterSupplier: true,
        component: () => import('../routes/Calendar/List'),
        models: [() => import('../models/calendar')],
      },
      {
        path: '/hpfm/mdm/calendar/detail-readOnly/:calendarId',
        FilterSupplier: true,
        component: () => import('../routes/Calendar/Detail/readOnly'),
        models: [() => import('../models/calendar')],
      },
      {
        path: '/hpfm/mdm/calendar/detail/:calendarId',
        FilterSupplier: true,
        component: () => import('../routes/Calendar/Detail'),
        models: [() => import('../models/calendar')],
      },
    ],
  },
  {
    path: '/pub/hpfm/mdm/calendar/detail/:calendarId',
    FilterSupplier: true,
    authorized: true,
    component: () => import('../routes/Calendar/Detail/readOnly'),
    models: [() => import('../models/calendar')],
  },

  {
    path: '/hpfm/mdm/country',
    models: [],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/mdm/country/list',
        FilterSupplier: true,
        component: () => import('../routes/Country'),
        models: [() => import('../models/country')],
      },
      {
        path: '/hpfm/mdm/country/region/:id/:code/:name',
        FilterSupplier: true,
        component: () => import('../routes/Region'),
        models: [() => import('../models/region')],
      },
    ],
  },
  {
    path: '/private/hpfm/mdm/country/region/:id/:code/:name',
    FilterSupplier: true,
    component: () => import('../routes/Region'),
    authorized: true,
    key: '/private/hpfm/mdm/country/region/:id/:code/:name',
    models: [() => import('../models/region')],
  },
  {
    path: '/private/hpfm/mdm/country/list',
    FilterSupplier: true,
    component: () => import('../routes/Country'),
    authorized: true,
    key: '/private/hpfm/mdm/country/list',
    models: [() => import('../models/country')],
  },
  {
    path: '/hpfm/mdm/currency',
    FilterSupplier: true,
    component: () => import('../routes/Currency'),
    models: [() => import('../models/currency')],
  },
  {
    path: '/hpfm/mdm/industry-category',
    FilterSupplier: true,
    component: () => import('../routes/IndustryCategory'),
    models: [() => import('../models/industryCategory')],
  },
  {
    path: '/hpfm/mdm/period',
    FilterSupplier: true,
    component: () => import('../routes/Period'),
    models: [() => import('../models/period')],
  },
  {
    path: '/hpfm/mdm/rate',
    FilterSupplier: true,
    component: () => import('../routes/Rate'),
    models: [() => import('../models/rate')],
  },
  {
    path: '/hpfm/mdm/rate-type',
    FilterSupplier: true,
    component: () => import('../routes/RateType'),
    models: [() => import('../models/rateType')],
  },
  {
    path: '/hpfm/mdm/tax-rate',
    FilterSupplier: true,
    component: () => import('../routes/TaxRate'),
    models: [() => import('../models/taxRate')],
  },
  {
    path: '/hpfm/mdm/uom',
    FilterSupplier: true,
    component: () => import('../routes/Uom'),
    models: [() => import('../models/uom')],
  },
  {
    path: '/hpfm/mdm/uom-type',
    FilterSupplier: true,
    component: () => import('../routes/UomType'),
    models: [() => import('../models/uomType')],
  },
  {
    path: '/hpfm/message',
    FilterSupplier: true,
    component: () => import('../routes/NewMessage'),
    models: [() => import('../models/message')],
  },
  {
    path: '/hpfm/message/user',
    FilterSupplier: true,
    component: () => import('../routes/NewMessage'),
    models: [() => import('../models/message')],
  },
  {
    path: '/hpfm/online',
    FilterSupplier: true,
    component: () => import('../routes/Online'),
    models: [() => import('../models/online')],
  },
  {
    path: '/private/hpfm/online',
    key: '/private/hpfm/online',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/Online'),
    models: [() => import('../models/online')],
  },
  {
    path: '/hpfm/org-info',
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/org-info',
        FilterSupplier: true,
        component: () => import('../routes/OrgInfo'),
        models: [() => import('../models/group')],
      },
      {
        path: '/hpfm/org-info/company',
        FilterSupplier: true,
        component: () => import('../routes/OrgInfo/Company'),
        models: [() => import('../models/company')],
      },
      {
        path: '/hpfm/org-info/group',
        FilterSupplier: true,
        component: () => import('../routes/OrgInfo/Group'),
        models: [() => import('../models/group')],
      },
      {
        path: '/hpfm/org-info/inventory-org',
        FilterSupplier: true,
        component: () => import('../routes/OrgInfo/InventoryOrg'),
        models: [() => import('../models/inventoryOrg')],
      },
      {
        path: '/hpfm/org-info/library-position',
        FilterSupplier: true,
        component: () => import('../routes/OrgInfo/LibraryPosition'),
        models: [() => import('../models/libraryPosition')],
      },
      {
        path: '/hpfm/org-info/operation-unit',
        FilterSupplier: true,
        component: () => import('../routes/OrgInfo/OperationUnit'),
        models: [() => import('../models/operationUnit')],
      },
      {
        path: '/hpfm/org-info/purchase-agent',
        FilterSupplier: true,
        component: () => import('../routes/OrgInfo/PurchaseAgent'),
        models: [() => import('../models/purchaseAgent')],
      },
      {
        path: '/hpfm/org-info/purchase-org',
        FilterSupplier: true,
        component: () => import('../routes/OrgInfo/PurchaseOrg'),
        models: [() => import('../models/purchaseOrg')],
      },
      {
        path: '/hpfm/org-info/store-room',
        FilterSupplier: true,
        component: () => import('../routes/OrgInfo/StoreRoom'),
        models: [() => import('../models/storeRoom')],
      },
    ],
  },
  {
    path: '/hpfm/permission',
    FilterSupplier: true,
    component: () => import('../routes/Permission'),
    models: [() => import('../models/permission')],
  },
  {
    path: '/private/hpfm/permission',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/Permission'),
    models: [() => import('../models/permission')],
  },
  {
    path: '/hpfm/platform-log',
    FilterSupplier: true,
    component: () => import('../routes/PlatformManager'),
    models: [() => import('../models/platformManager')],
  },
  {
    path: '/hpfm/profile',
    FilterSupplier: true,
    component: () => import('../routes/Profile/Site'),
    models: [() => import('../models/profile')],
  },
  {
    path: '/private/hpfm/profile',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/Profile/Site'),
    models: [() => import('../models/profile')],
  },
  {
    path: '/hpfm/profile-org',
    FilterSupplier: true,
    component: () => import('../routes/Profile/Org'),
    models: [() => import('../models/profileOrg')],
  },
  {
    path: '/private/hpfm/profile-org',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/Profile/Org'),
    models: [() => import('../models/profileOrg')],
  },
  {
    path: '/hpfm/prompt',
    FilterSupplier: true,
    component: () => import('../routes/Prompt'),
    models: [() => import('../models/prompt')],
  },
  {
    path: '/hpfm/prompt/import-data/:code',
    FilterSupplier: true,
    component: () => import('../routes/himp/CommentImport'),
    models: [],
  },

  {
    path: '/hpfm/rule-engine',
    models: [() => import('../models/ruleEngine')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/rule-engine/list',
        FilterSupplier: true,
        component: () => import('../routes/RuleEngine/List'),
        models: [() => import('../models/ruleEngine')],
      },
      {
        path: '/hpfm/rule-engine/create',
        FilterSupplier: true,
        component: () => import('../routes/RuleEngine/Detail'),
        models: [() => import('../models/ruleEngine')],
      },
      {
        path: '/hpfm/rule-engine/detail/:id',
        FilterSupplier: true,
        component: () => import('../routes/RuleEngine/Detail'),
        models: [() => import('../models/ruleEngine')],
      },
    ],
  },
  {
    path: '/hpfm/sql-execute',
    FilterSupplier: true,
    component: () => import('../routes/SqlExecute'),
    models: [() => import('../models/sqlExecute')],
  },
  {
    path: '/hpfm/static-text',
    models: [() => import('../models/staticText')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/static-text/list',
        FilterSupplier: true,
        component: () => import('../routes/StaticText/Site'),
        models: [() => import('../models/staticText')],
      },
      {
        path: '/hpfm/static-text/detail/:action',
        FilterSupplier: true,
        component: () => import('../routes/StaticText/Site/Detail'),
        models: [() => import('../models/staticText')],
      },
    ],
  },
  {
    path: '/hpfm/static-text-org',
    models: [() => import('../models/staticTextOrg')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/static-text-org/list',
        FilterSupplier: true,
        component: () => import('../routes/StaticText/Org'),
        models: [() => import('../models/staticTextOrg')],
      },
      {
        path: '/hpfm/static-text-org/detail/:action',
        FilterSupplier: true,
        component: () => import('../routes/StaticText/Org/Detail'),
        models: [() => import('../models/staticTextOrg')],
      },
    ],
  },
  {
    path: '/hpfm/tenant-log',
    FilterSupplier: true,
    component: () => import('../routes/TenantManager'),
    models: [() => import('../models/tenantManager')],
  },
  {
    path: '/private/hpfm/tenant-log',
    key: '/private/hpfm/tenant-log',
    authorized: true,
    FilterSupplier: true,
    component: () => import('../routes/TenantManager'),
    models: [() => import('../models/tenantManager')],
  },
  {
    path: '/hpfm/ui',
    models: [],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/ui/page',
        models: [],
        FilterSupplier: true,
        components: [
          {
            path: '/hpfm/ui/page/list',
            FilterSupplier: true,
            component: () => import('../routes/UI/Site/PageList'),
            models: [() => import('../models/uiPage')],
          },
          {
            path: '/hpfm/ui/page/detail/:pageCode',
            FilterSupplier: true,
            component: () => import('../routes/UI/Site/PageDetail'),
            models: [() => import('../models/uiPage')],
          },
        ],
      },
      {
        path: '/hpfm/ui/page-org',
        models: [],
        FilterSupplier: true,
        components: [
          {
            path: '/hpfm/ui/page-org/list',
            FilterSupplier: true,
            component: () => import('../routes/UI/Org/PageList'),
            models: [() => import('../models/uiPageOrg')],
          },
          {
            path: '/hpfm/ui/page-org/detail/:pageCode',
            FilterSupplier: true,
            component: () => import('../routes/UI/Org/PageDetail'),
            models: [() => import('../models/uiPageOrg')],
          },
        ],
      },
      {
        title: 'hzero.common.title.uiPagePreview',
        authorized: true,
        icon: 'search',
        path: '/hpfm/ui/page/common/:pageCode',
        FilterSupplier: true,
        component: () => import('../routes/UI/Common'),
        models: [],
      },
      {
        title: 'hzero.common.title.uiPagePreview',
        authorized: true,
        icon: 'search',
        path: '/hpfm/ui/page/preview/:pageCode',
        FilterSupplier: true,
        component: () => import('../routes/UI/Site/PagePreview'),
        models: [],
      },
    ],
  },
  {
    path: '/hpfm/value-list',
    models: [() => import('../models/valueList')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/value-list/list',
        FilterSupplier: true,
        component: () => import('../routes/ValueList'),
        models: [() => import('../models/valueList')],
      },
      {
        path: '/hpfm/value-list/detail/:lovId',
        FilterSupplier: true,
        component: () => import('../routes/ValueList/ValueDetail'),
        models: [() => import('../models/valueList')],
      },
      {
        path: '/hpfm/value-list/import-data/:code',
        FilterSupplier: true,
        component: () => import('../routes/himp/CommentImport'),
        models: [],
      },
    ],
  },
  {
    path: '/hpfm/customize',
    models: [() => import('../models/customize')],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/customize/list',
        models: [() => import('../models/customize')],
        FilterSupplier: true,
        component: () => import('../routes/Customize'),
      },
      {
        path: '/hpfm/customize/detail/:type/:id',
        models: [() => import('../models/customize')],
        FilterSupplier: true,
        component: () => import('../routes/Customize'),
      },
    ],
  },
  {
    path: '/hpfm/data-group',
    models: [],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/data-group/list',
        FilterSupplier: true,
        component: () => import('../routes/DataGroup/List'),
        models: [() => import('../models/dataGroup')],
      },
      {
        path: '/hpfm/data-group/detail/:id',
        FilterSupplier: true,
        component: () => import('../routes/DataGroup/Detail'),
        models: [() => import('../models/dataGroup')],
      },
    ],
  },
  {
    path: '/private/hpfm/data-group',
    key: '/private/hpfm/data-group',
    authorized: true,
    FilterSupplier: true,
    components: [
      {
        path: '/private/hpfm/data-group/list',
        key: '/private/hpfm/data-group/list',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/DataGroup/List'),
        models: [() => import('../models/dataGroup')],
      },
      {
        path: '/private/hpfm/data-group/detail/:id',
        key: '/private/hpfm/data-group/detail/:id',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/DataGroup/Detail'),
        models: [() => import('../models/dataGroup')],
      },
    ],
  },
  {
    path: '/hpfm/data-dimension-config',
    models: [],
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/data-dimension-config/list',
        FilterSupplier: true,
        component: () => import('../routes/DimensionConfig/List'),
        models: [() => import('../models/dimensionConfig')],
      },
      {
        path: '/hpfm/data-dimension-config/detail/:lovId',
        FilterSupplier: true,
        component: () => import('../routes/DimensionConfig/ValueDetail'),
        models: [() => import('../models/dimensionConfig')],
      },
    ],
  },
  {
    path: '/private/hpfm/data-dimension-config',
    key: '/private/hpfm/data-dimension-config',
    authorized: true,
    FilterSupplier: true,
    components: [
      {
        path: '/private/hpfm/data-dimension-config/list',
        key: '/private/hpfm/data-dimension-config/list',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/DimensionConfig/List'),
        models: [() => import('../models/dimensionConfig')],
      },
      {
        path: '/private/hpfm/data-dimension-config/detail/:lovId',
        key: '/private/hpfm/data-dimension-config/detail/:lovId',
        authorized: true,
        FilterSupplier: true,
        component: () => import('../routes/DimensionConfig/ValueDetail'),
        models: [() => import('../models/dimensionConfig')],
      },
    ],
  },
  {
    path: '/hpfm/ca-management',
    FilterSupplier: true,
    component: () => import('../routes/CaManagement'),
    models: [() => import('../models/caManagement')],
  },
  {
    path: '/hpfm/sync-to-outer-system',
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/sync-to-outer-system/list',
        FilterSupplier: true,
        component: () => import('../routes/SyncOuterSystem'),
      },
      {
        path: '/hpfm/sync-to-outer-system/detail/:syncId',
        FilterSupplier: true,
        component: () => import('../routes/SyncOuterSystem/LogList'),
      },
    ],
  },
  {
    path: '/hpfm/sys-tools',
    FilterSupplier: true,
    component: () => import('../routes/SysTools'),
  },
  {
    path: '/hpfm/ds-routes',
    FilterSupplier: true,
    components: [
      {
        key: '/hpfm/ds-routes',
        path: '/hpfm/ds-routes/list',
        exact: true,
        FilterSupplier: true,
        component: () => import('../routes/DsRoutes'),
      },
      {
        key: '/hpfm/ds-routes',
        path: '/hpfm/ds-routes/detail/:dsRouteId',
        FilterSupplier: true,
        component: () => import('../routes/DsRoutes/Detail'),
      },
    ],
  },
  // 通用模板管理
  {
    path: '/hpfm/general-template',
    FilterSupplier: true,
    components: [
      {
        path: '/hpfm/general-template/list',
        FilterSupplier: true,
        component: () => import('../routes/GeneralTemplate'),
      },
      {
        path: '/hpfm/general-template/detail/:action/:id',
        FilterSupplier: true,
        component: () => import('../routes/GeneralTemplate/Detail'),
      },
    ],
  },
  {
    path: '/hpfm/prompt-translate',
    models: [() => import('../models/promptTranslate.js')],
    component: () => import('../routes/PromptTranslate'),
    FilterSupplier: true,
  },
  {
    path: '/hpfm/prompt-translate/user',
    models: [() => import('../models/promptTranslate.js')],
    component: () => import('../routes/PromptTranslate'),
    FilterSupplier: true,
  },
  // 值集翻译配置
  {
    path: '/hpfm/value-set-translate/list',
    models: [],
    component: () => import('../routes/ValueSetTranslate'),
    FilterSupplier: true,
    priority: 100,
  },
  {
    path: '/hpfm/certificates-manage',
    models: [],
    component: () => import('../routes/CertificatesManage'),
  },
];
