const editSection = {
  DETAIL: 'SPCM.WORKSPACE_DETAIL.CARD',
  STAGE: 'SPCM.WORKSPACE_DETAIL.STAGE',
  SUBJECT: 'SPCM.WORKSPACE_DETAIL.SUBJECT',
  REBATE: 'SPCM.WORKSPACE_DETAIL.REBATE',
  CONTRACTREPLENISH: 'SPCM.WORKSPACE_DETAIL.CONTRACTREPLENISH',
  BUSINESSTERMS: 'SPCM.WORKSPACE_DETAIL.BUSINESSTERMS',
  TABLEEXTEND: 'SPCM.WORKSPACE_DETAIL.TABLEEXTEND',
  DISCOUNTRULE: 'SPCM.WORKSPACE_DETAIL.DISCOUNTRULE',
  REBATERULE: 'SPCM.WORKSPACE_DETAIL.REBATERULE',
  ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.ATTACHMENT',
  PARTNER: 'partnerInfo', // 标题卡片code
  SMARTABSTRACT: 'smartAbstract',
  SMARTREVIEW: 'smartReview',
  SIGNNODE: 'signNode',
};

const readOnlySection = {
  DETAIL: 'SPCM.WORKSPACE_DETAIL.CARD.READONLY',
  SUBJECT: 'SPCM.WORKSPACE_DETAIL.SUBJECT.READONLY',
  STAGE: 'SPCM.WORKSPACE_DETAIL.STAGE.READONLY',
  REBATE: 'SPCM.WORKSPACE_DETAIL.REBATE.READONLY',
  BUSINESSTERMS: 'SPCM.WORKSPACE_DETAIL.BUSINESSTERMS.READONLY',
  CONTRACTREPLENISH: 'SPCM.WORKSPACE_DETAIL.CONTRACTREPLENISH',
  TABLEEXTEND: 'SPCM.WORKSPACE_DETAIL.TABLEEXTEND.READONLY',
  DISCOUNTRULE: 'SPCM.WORKSPACE_DETAIL.DISCOUNTRULE.READONLY',
  REBATERULE: 'SPCM.WORKSPACE_DETAIL.REBATERULE.READONLY',
  ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.ATTACHMENT.READONLY',
  PARTNER: 'partnerInfo', // 标题卡片code
  SMARTABSTRACT: 'smartAbstract',
  SMARTREVIEW: 'smartReview',
  SIGNNODE: 'signNode',
};

export { editSection, readOnlySection };
