// 查询条件配置 静态
import intl from 'utils/intl';

export const getQueryConfig = () => {
  return {
    'SDAT.EVENT_UPDATE_SUMMARY_MONITOR_QUERY_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'enterpriseName',
          fieldCode: 'enterpriseName',
          fieldEditable: 1,
          fieldName: intl.get('sdat.eventUpdateSummary.view.model.monitorBusiness').d('监控企业'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 1,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          defaultFlag: 1,
          defaultSortedField: 'addMonitorTime',
          defaultSortedOrder: 'desc',
          filterName: intl.get('sdat.eventUpdateSummary.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'addMonitorTime',
              fieldCode: 'addMonitorTime',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.eventUpdateSummary.model.monitorTime`).d('首次监控时间'),
              fieldVisible: 1,
              modelCode: 'addMonitorTime',
              proDefaultFlag: 0,
              showFlag: 0,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 0,
              },
              rank: 4,
              gridSeq: 4,
              sortedFlag: 1,
              usedFlag: 1,
              fixedFlag: 1,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'monitorStatus',
              fieldCode: 'monitorStatus',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventUpdateSummary.view.model.monitorStatus').d('监控状态'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'monitorStatus',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.COMPANY_MONITOR_STATUS',
              },
              gridSeq: 2,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['LIKE'],
              fieldAlias: 'appId',
              fieldCode: 'appId',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventUpdateSummary.model.appId').d('应用ID'),
              fieldVisible: 1,
              modelCode: 'appId',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'INPUT',
                linkNewWindow: 0,
              },
              gridSeq: 3,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 3,
            },
          ].filter(Boolean),
        },
      ],
    },
    'SDAT.EVENT_UPDATE_SUMMARY_RISKLIST_QUERY_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [],
      systemFilters: [
        {
          defaultFlag: 1,
          defaultSortedField: 'lastUpdateTime',
          defaultSortedOrder: 'desc',
          filterName: intl.get('sdat.riskDefinition.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'scope',
              fieldCode: 'scope',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.riskDefinition.model.applicationScope`).d('适用范围'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'scope',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.RISK_DEFINITION_SCOPE',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'dateRange',
              fieldCode: 'dateRange',
              fieldEditable: 1,
              fieldName: intl.get('sdat.riskDefinition.model.lastUpdateTime').d('最后更新时间'),
              fieldVisible: 1,
              modelCode: 'dateRange',
              proDefaultFlag: 0,
              showFlag: 0,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1,
              },
              rank: 4,
              gridSeq: 6,
              sortedFlag: 1,
              usedFlag: 1,
              fixedFlag: 1,
            },
          ].filter(Boolean),
        },
      ],
    },
  };
};
