// 查询条件配置 静态
import intl from 'utils/intl';

export const getQueryConfig = () => {
  return {
    'SDAT.RISK_SCAN_SCHEMA_CONFIG_SEARCH_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        // {
        //   fieldAlias: 'companyName',
        //   fieldCode: 'companyName',
        //   fieldEditable: 1,
        //   fieldName: intl.get('sdat.riskScanConfig.model.businessName').d('企业名称'),
        //   fieldVisible: 1,
        //   gridSeq: 0,
        //   showFlag: 0,
        //   sortedFlag: 0,
        //   customComparisonSet: ['LIKE'],
        //   widget: {
        //     fieldWidget: 'INPUT',
        //     linkNewWindow: 0,
        //     multipleFlag: 0,
        //   },
        // },
      ],
      systemFilters: [
        {
          defaultFlag: 1,
          defaultSortedField: 'lastUpdateDate',
          defaultSortedOrder: 'desc',
          filterName: intl.get('sdat.riskScanConfig.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'autoFrequency',
              fieldCode: 'autoFrequency',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.riskScanConfig.model.strategyConfig`).d('扫描策略配置'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'autoFrequency',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.WB2_SCAN_PLAN_FREQUENCY_TYPE',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'scanObjectType',
              fieldCode: 'scanObjectType',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.riskScanConfig.model.addType`).d('扫描对象添加方式'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'scanObjectType',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.WB2_SCAN_OBJECT_TYPE',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'scanScopeType',
              fieldCode: 'scanScopeType',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.riskScanConfig.model.applicationScope`).d('适用范围'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'scanScopeType',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.WB2_SCAN_SCOPE_TYPE',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'dateRange',
              fieldCode: 'dateRange',
              fieldEditable: 1,
              fieldName: intl.get('sdat.riskScanConfig.model.lastUpdateTime').d('最后更新时间'),
              fieldVisible: 1,
              modelCode: 'dateRange',
              proDefaultFlag: 0,
              showFlag: 0,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1,
              },
              rank: 4,
              gridSeq: 6,
              sortedFlag: 1,
              usedFlag: 1,
              fixedFlag: 1,
            },
          ].filter(Boolean),
        },
      ],
    },
  };
};
