const oldUnitCodeList = {
  DETAIL: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.DETAIL',
  PARTNER: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.PARTNER',
  SUBJECT: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.SUBJECT',
  REBATE: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.REBATE',
  STAGE: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.STAGE',
};

const newUnitCodeList = {
  DETAIL: 'SPCM.CONTRACT.NEW_CONTROL.DETAIL',
  PARTNER: 'SPCM.CONTRACT.NEW_CONTROL.PARTNER',
  SUBJECT: 'SPCM.CONTRACT.NEW_CONTROL.SUBJECT',
  REBATE: 'SPCM.CONTRACT.NEW_CONTROL.REBATE',
  STAGE: 'SPCM.CONTRACT.NEW_CONTROL.STAGE',
};

const readOnlyCodeList = {
  DETAIL: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.DETAIL.READONLY',
  SUBJECT: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.SUBJECT.READONLY',
  PARTNER: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.PARTNER.READONLY',
  REBATE: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.REBATE.READONLY',
  STAGE: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.STAGE.READONLY',
};

const readOnlyWFCodeList = {
  SUBJECT: 'SPCM.WORKSPACE.APPROVAL.SUBJECT.READONLY',
  PARTNER: 'SPCM.WORKSPACE.APPROVAL.PARTNER.READONLY',
  REBATE: 'SPCM.WORKSPACE.APPROVAL.REBATE.READONLY',
  STAGE: 'SPCM.WORKSPACE.APPROVAL.STAGE.READONLY',
  BUSINESSTERMS: 'SPCM.WORKSPACE.APPROVAL.BUSINESSTERMS.READONLY',
  CONTRACTREPLENISH: 'SPCM.WORKSPACE.APPROVAL.CONTRACTREPLENISH',
  ATTACHMENT: {
    PURCHASER_ATTACHMENT: 'SPCM.WORKSPACE.APPROVAL.ATTACHMENT_FORM',
    ARCHIVE_ATTACHMENT: 'SPCM.WORKSPACE.APPROVAL.ARCHIVE_ATTACHMENT_FORM',
    ESIGN_ATTACHMENT: 'SPCM.WORKSPACE.APPROVAL.ELECTRONIC_FORM',
    CUSTOM_ATTACHMENT: 'SPCM.WORKSPACE.APPROVAL.CUSTOM_ATTACHMENT_FORM',
    OFFLINE_MUTUAL_ATTACHMENT: 'SPCM.WORKSPACE.APPROVAL.OFFLINE_MUTUAL_ATTACHMENT_FORM',
  },
  ATTACHMENTCARD: {
    ATTACHMENTCARD1: 'SPCM.WORKSPACE.APPROVAL.ATTACHMENT_CARD',
    ATTACHMENTCARD2: 'SPCM.WORKSPACE.APPROVAL.ATTACHMENT_CARD2',
  }, // 附件标题卡片
  HEADBTN: 'SPCM.WORKSPACE.APPROVAL.BTN_GROUP',
  SMARTREVIEW: 'SPCM.WORKSPACE.APPROVAL.SMARTREVIEW_C',
};

/**
 * 协议状态对应的审批方式存储字段
 */
export const statusApproveMap = {
  SUBMITTED: 'approvalMethod',
  APPROVAL_PENDING: 'confirmApproveMethod',
  ARCHIVE_TO_APPROVAL: 'archiveApproveMethod',
  INVALID_TO_APPROVAL: 'invalidApproveMethod',
  CHANGE_TO_APPROVAL: 'changeApproveMethod',
  TERMINATION_TO_APPROVAL: 'terminationApproveMethod',
  EFFECTED_TO_APPROVAL: 'confirmEffectApproveMethod',
};

export const editCustomCode = {
  PURCHASER_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.ATTACHMENT_FORM',
  ARCHIVE_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.ARCHIVE_ATTACHMENT_FORM',
  ESIGN_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.ESIGN_ATTACHMENT_FORM',
  CUSTOM_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.CUSTOM_ATTACHMENT_FORM',
  OFFLINE_MUTUAL_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.OFFLINE_MUTUAL_ATTACHMENT_FORM',
};

export const viewCustomCode = {
  PURCHASER_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.ATTACHMENT_FORM_READONLY',
  ARCHIVE_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.ARCHIVE_ATTACHMENT_FORM_READONLY',
  ESIGN_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.ESIGN_ATTACHMENT_FORM_READONLY',
  CUSTOM_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.CUSTOM_ATTACHMENT_FORM_READONLY',
  OFFLINE_MUTUAL_ATTACHMENT: 'SPCM.WORKSPACE_DETAIL.OFFLINE_MUTUAL_ATTACHMENT_FORM_READONLY',
};

export { oldUnitCodeList, newUnitCodeList, readOnlyCodeList, readOnlyWFCodeList };
