export const protocalUnitCode = {
  history: 'SMAL.AGREEMENT_MANAGEMENT.HISTORY_FORM',
  edit: 'SMAL.AGREEMENT_MANAGEMENT.PROTOCAL_FORM',
  view: 'SMAL.AGREEMENT_MANAGEMENT.PROTOCAL_ONLYREAD',
};

export const protocalDetailCode = {
  LIST: 'SMAL.AGREEMENT_MANAGEMENT.DETAIL',
  SEARCH_FORM: 'SMAL.AGREEMENT_MANAGEMENT.DETAILSEARCH',
};

export const batchProtocalCode = {
  BATCH_PRICE_FORM: 'SMAL.AGREEMENT_MANAGEMENT.IMOIRT_PRICE_LIB_NEW_FORM',
  BATCH_MANUAL_FORM: 'SMAL.AGREEMENT_MANAGEMENT.IMPORT_MANUAL_NEW_FORM1',
};

export const protManageBtns = {
  top: 'SMAL.AGREEMENT_MANAGEMENT.BTNS', // 顶部按钮
  workbenchTop: 'SAGM.WORKBENCH.MAIN.BTNS', // 工作台顶部按钮
  detail: 'SMALL.AGREEMENT_MANAGE.BTNS.DETAIL', // 明细列表
  product: 'SMALL.AGREEMENT_MANAGE.BTNS.PRODUCT', // 商品列表
  history: 'SMALL.AGREEMENT_MANAGE.BTNS.HISTORY', // 历史列表
};
