// 查询条件配置 静态
import intl from 'utils/intl';

export const getQueryConfig = () => {
  return {
    'SDAT.EVENT_UPDATE_SUMMARY_DETAIL_QUERY_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'enterpriseName',
          fieldCode: 'enterpriseName',
          fieldEditable: 1,
          fieldName: intl.get('sdat.riskControl.view.title.queryKeyValue').d('关键字查询'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 1,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          // defaultFlag: 1,
          // defaultSortedField: 'lastUpdateTime',
          // defaultSortedOrder: 'desc',
          filterName: intl.get('sdat.eventUpdateSummary.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            // {
            //   customComparisonSet: ['='],
            //   fieldAlias: 'riskStatus',
            //   fieldCode: 'riskStatus',
            //   fieldEditable: 1,
            //   fieldName: intl.get('sdat.eventUpdateSummary.view.model.riskStatus').d('风险状态'),
            //   fieldVisible: 1,
            //   lovInfo: { displayField: 'meaning', valueField: 'value' },
            //   modelCode: 'riskStatus',
            //   proDefaultFlag: 0,
            //   showFlag: 1,
            //   widget: {
            //     fieldWidget: 'SELECT',
            //     linkNewWindow: 0,
            //     lovInfo: { displayField: 'meaning', valueField: 'value' },
            //     sourceCode: 'SDAT.MONITOR_RISK_TYPE',
            //   },
            //   gridSeq: 1,
            //   sortedFlag: 0,
            //   fixedFlag: 1,
            //   usedFlag: 1,
            //   rank: 1,
            // },
            {
              customComparisonSet: ['='],
              fieldAlias: 'level',
              fieldCode: 'level',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventUpdateSummary.view.model.eventLevel').d('风险等级'),
              fieldVisible: 1,
              // lovInfo: { displayField: 'tenantName', valueField: 'tenantId' },
              modelCode: 'level',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.WORKBENCH_EVENT_LEVEL',
                multipleFlag: 1,
              },
              gridSeq: 3,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 3,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'type',
              fieldCode: 'type',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventUpdateSummary.view.model.riskType').d('风险类型'),
              fieldVisible: 1,
              lovInfo: { displayField: 'themeName', valueField: 'themeCode' },
              modelCode: 'type',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'LOV',
                linkNewWindow: 0,
                sourceCode: 'SDAT.MONITOR_EVENT_TYPE',
                multipleFlag: 1,
                queryField: 'themeName',
              },
              gridSeq: 6,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 6,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'status',
              fieldCode: 'status',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventUpdateSummary.model.dealStatus').d('处置状态'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'status',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.WORKBENCH_EVENT_STATUS',
                multipleFlag: 1,
              },
              gridSeq: 4,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 4,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'updateTime',
              fieldCode: 'updateTime',
              fieldEditable: 1,
              fieldName: intl
                .get('sdat.eventUpdateSummary.view.model.lastUpdateTime')
                .d('最后更新时间'),
              fieldVisible: 1,
              modelCode: 'updateTime',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1, // 是否是range
              },
              rank: 3,
              gridSeq: 3,
              sortedFlag: 1,
              fixedFlag: 1,
              usedFlag: 1,
            },
            // {
            //   customComparisonSet: ['IN'],
            //   fieldAlias: 'dateProd',
            //   fieldCode: 'dateProd',
            //   fieldEditable: 1,
            //   fieldName: intl.get('sdat.eventUpdateSummary.view.model.dateProd').d('执行时间范围'),
            //   fieldVisible: 1,
            //   modelCode: 'dateProd',
            //   proDefaultFlag: 0,
            //   showFlag: 1,
            //   widget: {
            //     dateFormat: 'YYYY-MM-DD',
            //     fieldWidget: 'DATE_PICKER',
            //     linkNewWindow: 0,
            //     multipleFlag: 1, // 是否是range
            //   },
            //   rank: 4,
            //   gridSeq: 4,
            //   sortedFlag: 0,
            //   fixedFlag: 1,
            //   usedFlag: 1,
            // },
          ].filter(Boolean),
        },
      ],
    },
  };
};
