// 查询条件配置 静态
import intl from 'utils/intl';

export const getQueryConfig = () => {
  return {
    'SDAT.PLATFORM_REPORT_TEMPLATE_MANAGEMENT_LIST': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'name',
          fieldCode: 'name',
          fieldEditable: 1,
          fieldName: intl.get('sdat.templateManage.model.templateNameOrCode').d('模板编码、名称'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 0,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          defaultFlag: 1,
          // defaultSortedField: 'offerDate',
          // defaultSortedOrder: 'asc',
          filterName: intl.get('sdat.templateManage.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'level',
              fieldCode: 'level',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.templateManage.model.templateLevel`).d('模板层级'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'level',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.REPORT_CARD_LEVEL',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'groupCode',
              fieldCode: 'groupCode',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.templateManage.model.group`).d('模板分组'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'groupCode',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.REPORT_TEMPLATE_GROUP',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 3,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'defaultFlag',
              fieldCode: 'defaultFlag',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.templateManage.model.isDefault`).d('是否默认'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'defaultFlag',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.REPORT_TEMPLATE_ISDEFAULT',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 4,
            },
            // {
            //   customComparisonSet: ['IN'],
            //   fieldAlias: 'lastScanTime',
            //   fieldCode: 'lastScanTime',
            //   fieldEditable: 1,
            //   fieldName: intl.get(`sdat.templateManage.model.lastScanningTime`).d('上次扫描时间'),
            //   fieldVisible: 1,
            //   modelCode: 'lastScanTime',
            //   proDefaultFlag: 0,
            //   showFlag: 1,
            //   widget: {
            //     dateFormat: 'YYYY-MM-DD',
            //     fieldWidget: 'DATE_PICKER',
            //     linkNewWindow: 0,
            //     multipleFlag: 1,
            //   },
            //   rank: 5,
            //   gridSeq: 5,
            //   sortedFlag: 0,
            //   usedFlag: 1,
            //   fixedFlag: 0,
            // },
          ].filter(Boolean),
        },
      ],
    },
  };
};
