// 查询条件配置 静态
import intl from 'utils/intl';

export const getQueryConfig = () => {
  return {
    'SDAT.RISK_CONTROL_MONITOR_DOMESTIC_CREDIT_SEARCH_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'enterpriseNameAndCode',
          fieldCode: 'enterpriseNameAndCode',
          fieldEditable: 1,
          fieldName: intl.get('sdat.riskScanConfig.model.nameOrCode').d('名称、编码'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 0,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          defaultFlag: 1,
          filterName: intl.get('sdat.riskScanConfig.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'effectiveFlag',
              fieldCode: 'effectiveFlag',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.riskScanConfig.model.status`).d('状态'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'effectiveFlag',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'HPFM.EFFECTIVE_FLAG',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'dateRange',
              fieldCode: 'dateRange',
              fieldEditable: 1,
              fieldName: intl.get('sdat.riskScanConfig.model.invalidTime').d('失效时间'),
              fieldVisible: 1,
              modelCode: 'dateRange',
              proDefaultFlag: 0,
              showFlag: 0,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1,
              },
              rank: 4,
              gridSeq: 6,
              sortedFlag: 1,
              usedFlag: 0,
              fixedFlag: 0,
            },
          ].filter(Boolean),
        },
      ],
    },
    'SDAT.RISK_CONTROL_MONITOR_OVERSEAS_CREDIT_SEARCH_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'enterpriseNameAndCode',
          fieldCode: 'enterpriseNameAndCode',
          fieldEditable: 1,
          fieldName: intl.get('sdat.riskScanConfig.model.nameOrCode').d('名称、编码'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 0,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          defaultFlag: 1,
          filterName: intl.get('sdat.riskScanConfig.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'effectiveFlag',
              fieldCode: 'effectiveFlag',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.riskScanConfig.model.status`).d('状态'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'effectiveFlag',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'HPFM.EFFECTIVE_FLAG',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'dateRange',
              fieldCode: 'dateRange',
              fieldEditable: 1,
              fieldName: intl.get('sdat.riskScanConfig.model.invalidTime').d('失效时间'),
              fieldVisible: 1,
              modelCode: 'dateRange',
              proDefaultFlag: 0,
              showFlag: 0,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1,
              },
              rank: 4,
              gridSeq: 6,
              sortedFlag: 1,
              usedFlag: 0,
              fixedFlag: 0,
            },
          ].filter(Boolean),
        },
      ],
    },
    'SDAT.RISK_CONTROL_MONITOR_FINANCIAL_MONITOR_SEARCH_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'enterpriseNameAndCode',
          fieldCode: 'enterpriseNameAndCode',
          fieldEditable: 1,
          fieldName: intl.get('sdat.riskScanConfig.model.nameOrCode').d('名称、编码'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 0,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          defaultFlag: 1,
          filterName: intl.get('sdat.riskScanConfig.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'effectiveFlag',
              fieldCode: 'effectiveFlag',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.riskScanConfig.model.status`).d('状态'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'scope',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.RISK_DEFINITION_SCOPE',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'dateRange',
              fieldCode: 'dateRange',
              fieldEditable: 1,
              fieldName: intl.get('sdat.riskScanConfig.model.invalidTime').d('失效时间'),
              fieldVisible: 1,
              modelCode: 'dateRange',
              proDefaultFlag: 0,
              showFlag: 0,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1,
              },
              rank: 4,
              gridSeq: 6,
              sortedFlag: 1,
              usedFlag: 0,
              fixedFlag: 0,
            },
          ].filter(Boolean),
        },
      ],
    },
    'SDAT.RISK_CONTROL_MONITOR_BUSINESS_INDICATOR_SEARCH_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'enterpriseNameAndCode',
          fieldCode: 'enterpriseNameAndCode',
          fieldEditable: 1,
          fieldName: intl.get('sdat.riskScanConfig.model.nameOrCode').d('名称、编码'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 0,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          defaultFlag: 1,
          filterName: intl.get('sdat.riskScanConfig.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'effectiveFlag',
              fieldCode: 'effectiveFlag',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.riskScanConfig.model.status`).d('状态'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'effectiveFlag',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'HPFM.EFFECTIVE_FLAG',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'dateRange',
              fieldCode: 'dateRange',
              fieldEditable: 1,
              fieldName: intl.get('sdat.riskScanConfig.model.invalidTime').d('失效时间'),
              fieldVisible: 1,
              modelCode: 'dateRange',
              proDefaultFlag: 0,
              showFlag: 0,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1,
              },
              rank: 4,
              gridSeq: 6,
              sortedFlag: 1,
              usedFlag: 0,
              fixedFlag: 0,
            },
          ].filter(Boolean),
        },
      ],
    },
    'SDAT.RISK_CONTROL_MONITOR_DISASTER_MONITOR_SEARCH_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'enterpriseNameAndCode',
          fieldCode: 'enterpriseNameAndCode',
          fieldEditable: 1,
          fieldName: intl.get('sdat.riskScanConfig.model.nameOrCode').d('名称、编码'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 0,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          defaultFlag: 1,
          filterName: intl.get('sdat.riskScanConfig.placeholder.defaultSelected').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'effectiveFlag',
              fieldCode: 'effectiveFlag',
              fieldEditable: 1,
              fieldName: intl.get(`sdat.riskScanConfig.model.status`).d('状态'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'effectiveFlag',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'HPFM.EFFECTIVE_FLAG',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 2,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'dateRange',
              fieldCode: 'dateRange',
              fieldEditable: 1,
              fieldName: intl.get('sdat.riskScanConfig.model.invalidTime').d('失效时间'),
              fieldVisible: 1,
              modelCode: 'dateRange',
              proDefaultFlag: 0,
              showFlag: 0,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1,
              },
              rank: 4,
              gridSeq: 6,
              sortedFlag: 1,
              usedFlag: 0,
              fixedFlag: 0,
            },
          ].filter(Boolean),
        },
      ],
    },
  };
};
