#!/bin/bash
set -e

find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_BASE_PATH $BUILD_BASE_PATH g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_API_HOST $BUILD_API_HOST g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_CLIENT_ID $BUILD_CLIENT_ID g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_WEBSOCKET_HOST $BUILD_WEBSOCKET_HOST g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_SRC_WEBSOCKET_HOST $BUILD_SRC_WEBSOCKET_HOST g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_PLATFORM_VERSION $BUILD_PLATFORM_VERSION g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_SRM_MALL_HOST $BUILD_SRM_MALL_HOST g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_LOGIN_URL $BUILD_LOGIN_URL g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_LOGOUT_URL $BUILD_LOGOUT_URL g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_PUBLIC_BUCKET $PUBLIC_BUCKET g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_PRIVATE_BUCKET $PRIVATE_BUCKET g"
find /usr/share/nginx/html -name '*.css' | xargs sed -i "s BUILD_PUBLIC_URL $BUILD_PUBLIC_URL g"
find /usr/share/nginx/html -path "/usr/share/nginx/html/packages" -prune -type f -o -name "*.js" | xargs sed -i "s BUILD_PUBLIC_URL $BUILD_PUBLIC_URL g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_PUBLIC_URL $BUILD_PUBLIC_URL g"
find /usr/share/nginx/html -name '*.js' | xargs sed -i "s BUILD_SRM_AMKT_HOST $BUILD_SRM_AMKT_HOST g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_SRM_AMKT_HOST $BUILD_SRM_AMKT_HOST g"
find /usr/share/nginx/html -name '*.js' | xargs sed -i "s BUILD_CUSZ_ADD_FIELD $BUILD_CUSZ_ADD_FIELD g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_CUSZ_ADD_FIELD $BUILD_CUSZ_ADD_FIELD g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_DATA_RANGERS_APP_ID $BUILD_DATA_RANGERS_APP_ID g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_ENV_NAME $BUILD_ENV_NAME g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_HELPROBOT_WECHAT_ICON $BUILD_HELPROBOT_WECHAT_ICON g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_CHUNK_UPLOAD_ENABLE $BUILD_CHUNK_UPLOAD_ENABLE g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_HZERO_PLATFORM_CUSZ_DATA_MIGRATE_ENABLE $BUILD_HZERO_PLATFORM_CUSZ_DATA_MIGRATE_ENABLE g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_HMDE_DATA_MIGRATE_ENABLE $BUILD_HMDE_DATA_MIGRATE_ENABLE g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_HRPT_DATA_MIGRATE_ENABLE $BUILD_HRPT_DATA_MIGRATE_ENABLE g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_WEB_PRO_ID $BUILD_WEB_PRO_ID g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_DOCFLOW_FLAG $BUILD_DOCFLOW_FLAG g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_YQCLOUD_POLL_TIME_MINUTE $BUILD_YQCLOUD_POLL_TIME_MINUTE g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_YQCLOUD_POLL_TIME_FLAG $BUILD_YQCLOUD_POLL_TIME_FLAG g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s SYSTEM_AUTO_API_HOST ${SYSTEM_AUTO_API_HOST:-false} g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_FILE_PHYSICS_DELETE_FLAG $BUILD_FILE_PHYSICS_DELETE_FLAG g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_SUPPLY_CHAIN_FINANCE_URL $BUILD_SUPPLY_CHAIN_FINANCE_URL g"
find /usr/share/nginx/html -name '*.js' | xargs sed -i "s BUILD_HMDE_ADD_FIELD $BUILD_HMDE_ADD_FIELD g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_HMDE_ADD_FIELD $BUILD_HMDE_ADD_FIELD g"
find /usr/share/nginx/html -name '*.js' | xargs sed -i "s BUILD_HRPT_ADD_FIELD $BUILD_HRPT_ADD_FIELD g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_HRPT_ADD_FIELD $BUILD_HRPT_ADD_FIELD g"
find /usr/share/nginx/html -name '*.js' | xargs sed -i "s BUILD_CUSZ_EXPORT_RECORD $BUILD_CUSZ_EXPORT_RECORD g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_CUSZ_EXPORT_RECORD $BUILD_CUSZ_EXPORT_RECORD g"
find /usr/share/nginx/html -name '*.js' | xargs sed -i "s BUILD_HMSG_MESSAGE_FILTER_CONTENT $BUILD_HMSG_MESSAGE_FILTER_CONTENT g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_HMSG_MESSAGE_FILTER_CONTENT $BUILD_HMSG_MESSAGE_FILTER_CONTENT g"
find /usr/share/nginx/html -name '*.js' | xargs sed -i "s BUILD_PORTAL_CUSTOMER_SERVICE_BUTTON $BUILD_PORTAL_CUSTOMER_SERVICE_BUTTON g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_PORTAL_CUSTOMER_SERVICE_BUTTON $BUILD_PORTAL_CUSTOMER_SERVICE_BUTTON g"
find /usr/share/nginx/html -name '*.js' | xargs sed -i "s BUILD_AUTO_LOGOUT_METHOD $BUILD_AUTO_LOGOUT_METHOD g"
find /usr/share/nginx/html -name '*.html' | xargs sed -i "s BUILD_AUTO_LOGOUT_METHOD $BUILD_AUTO_LOGOUT_METHOD g"
exec "$@"
