const source = 'src';
const dist = 'lib';

function getExposesByFiles(files) {
  return files.reduce((result, file) => {
    result[`./${dist}/${file}`] = `./${source}/${file}`;
    return result;
  }, {});
}

module.exports = {
  hzeroMS: {
    exposes: {
      ...getExposesByFiles([
        'components/ApproveButton',
        'components/ApproveModal',
        'components/ApprovalReply',
        'components/ApproveRecord',
        'components/ApproveRecordGroup',
        'components/ApproveRecordSimple',
        'components/C7NUpload',
        'components/Charts/autoHeight',
        'components/Charts/index.less',
        'components/CollapseForm',
        'components/ContactLov',
        'components/CaptchaButton',
        'components/CustomizeContext/C7nCustomizeContext',
        'components/CustomizeContext/H0CustomizeContext',
        'components/DocFlow',
        'components/DoubleTabs',
        'components/DynamicButtons',
        'components/EditTable',
        'components/EmbedPage',
        'components/ExcelExportPro',
        'components/FilterBarTable',
        'components/FilterBarTable/FilterBar',
        'components/Flex/FlexFields/utils',
        'components/Flex/FlexFields/withFlexFields',
        'components/Flex/Toolbox/withToolbox',
        'components/Guide',
        'components/Guide/injectGuideList',
        'components/HelpDocument',
        'components/HelpRobot',
        'components/HelpRobot/chatProvider',
        'components/Icons',
        'components/Import',
        'components/IMChatDraggable',
        'components/LeadLink',
        'components/LovSrm',
        'components/LovSrm/index.less',
        'components/MarmotDownloadButton',
        'components/MarmotScript/MarmotScriptButton',
        'components/MarmotScript/MarmotScriptEditor',
        'components/MultipleTextSplitInput',
        'components/OperationRecord',
        'components/OperationRecordCux',
        'components/PortalCard',
        'components/PortalCard/util',
        'components/PositionAnchor',
        'components/Precision/C7nPrecisionInputNumber',
        'components/Precision/PrecisionProvider',
        'components/PrintProButton',
        'components/RadioGroup',
        'components/SearchBarTable',
        'components/SearchBarTable/SearchBar',
        'components/SearchBarTable/util',
        'components/SearchBarTable/util/cache',
        'components/SearchPage',
        'components/Section',
        'components/SupplierLov',
        'components/Table',
        'components/Upload',
        'components/Upload/index',
        'components/Upload/UploadButton',
        'components/WebUploader',
        'components/PermissionButton',
        'components/ExpressionEngine',
        'components/ExpressionEngineRule',
        'components/RelTable',
        'components/SrmOperationRecord',
        'components/UrlAttachment',
        'components/AFCards',
        'utils/c7nUiConfig',
        'utils/config',
        'utils/CustomizeProvider',
        'utils/defaultConfig',
        'utils/intl',
        'utils/intl/formatterCollections',
        'utils/intl/LocaleProviderAsync',
        'utils/loadUiConfig',
        'utils/less-polyfill',
        'utils/utils',
        'utils/scuxUtils',
        'services/MarmotDownloadButtonServices',
        'utils/workflow',
      ]),
    },
    splitChunks: {
      cacheGroups: {
        common: {
          minChunks: 2,
          priority: -20,
          chunks: 'initial',
          name: 'chunk-common',
          reuseExistingChunk: true,
        },
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          priority: -10,
          name: 'chunk-vendors',
          chunks: 'async',
        },
        'regl': {
          test: /[\\/]node_modules[\\/]regl[\\/]/,
          priority: 100,
          name: 'regl',
        },
        'jquery': {
          test: /[\\/]node_modules[\\/]jquery[\\/]/,
          priority: 100,
          name: 'jquery',
        },
        'esprima': {
          test: /[\\/]node_modules[\\/]esprima[\\/]/,
          priority: 100,
          name: 'esprima',
        },
        'antv': {
          test: /[\\/]node_modules[\\/]@antv[\\/]/,
          priority: 100,
          name: 'antv',
        },
        'jshint': {
          test: /[\\/]node_modules[\\/]jshint[\\/]/,
          priority: 100,
          name: 'jshint',
        },
        'highlight': {
          test: /[\\/]node_modules[\\/]highlight.js[\\/]/,
          priority: 100,
          name: 'highlight',
        },
        'refractor': {
          test: /[\\/]node_modules[\\/]refractor[\\/]/,
          priority: 100,
          name: 'refractor',
        },
        'react-beautiful-dnd': {
          test: /[\\/]node_modules[\\/]react-beautiful-dnd[\\/]/,
          priority: 100,
          name: 'react-beautiful-dnd',
        },
        'react-dom': {
          test: /[\\/]node_modules[\\/]react-dom[\\/]/,
          priority: 100,
          name: 'react-dom',
        },
        'mobx': {
          test: /[\\/]node_modules[\\/]mobx[\\/]/,
          priority: 100,
          name: 'mobx',
        },
        'lodash': {
          test: /[\\/]node_modules[\\/]lodash[\\/](?!lodash.js)/,
          priority: 100,
          name: 'lodash',
        },
        'lodash-all': {
          test: /[\\/]node_modules[\\/]lodash[\\/]lodash.js/,
          priority: 100,
          name: 'lodash-all',
        },
        'boot': {
          test: /src[\\/](assets|utils|models|services)[\\/]/,
          priority: 100,
          name: 'boot',
          reuseExistingChunk: true,
        },
        'boot-components': {
          test: /src[\\/](components|)[\\/]/,
          priority: 100,
          name: 'boot-components',
        },
        'seach-bar-table-components': {
          test: /src[\\/]components[\\/](SearchBarTable|FilterBarTable)[\\/]/,
          priority: 110,
          name: 'seach-bar-table-components',
        },
        'flex-components': {
          test: /src[\\/]components[\\/]Flex[\\/]/,
          priority: 110,
          name: 'flex-components',
        },
        'c7n-upload-components': {
          test: /src[\\/]components[\\/]C7NUpload[\\/]/,
          priority: 110,
          name: 'c7n-upload-components',
        },
      },
    },
  },
};
