const oldUnitCodeList = {
  DETAIL: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.DETAIL',
  PARTNER: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.PARTNER',
  SUBJECT: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.SUBJECT',
  REBATE: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.REBATE',
  STAGE: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.STAGE',
};

const newUnitCodeList = {
  DETAIL: 'SPCM.CONTRACT.NEW_CONTROL.DETAIL',
  PARTNER: 'SPCM.CONTRACT.NEW_CONTROL.PARTNER',
  SUBJECT: 'SPCM.CONTRACT.NEW_CONTROL.SUBJECT',
  REBATE: 'SPCM.CONTRACT.NEW_CONTROL.REBATE',
  STAGE: 'SPCM.CONTRACT.NEW_CONTROL.STAGE',
};

const readOnlyCodeList = {
  DETAIL: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.DETAIL.READONLY',
  SUBJECT: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.SUBJECT.READONLY',
  PARTNER: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.PARTNER.READONLY',
  REBATE: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.REBATE.READONLY',
  STAGE: 'SPCM.PURCHASE_CONTRACT_MAINTAIN.STAGE.READONLY',
};

export { oldUnitCodeList, newUnitCodeList, readOnlyCodeList };
