// 关系对象类型值集
export const valueList = {
  MASTER: 'MASTER', // 主
  SLAVE_MASTER: 'SLAVE_MASTER', // 从主
  LINK: 'LINK', // 关联
  MASTER_SLAVE: 'MASTER_SLAVE', // 主从
  REVERSE_LINK: 'REVERSE_LINK', // 反向关联
  REL_LINK: 'REL_LINK',
  REL_REVERSE_LINK: 'REL_REVERSE_LINK',
  REL_MASTER_SLAVE: 'REL_MASTER_SLAVE',
  REL_SLAVE_MASTER: 'REL_SLAVE_MASTER',
};
