// 仅替换标签符号<>
export const MSG_TYPE = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  FILE: 'FILE',
  ASSISTANT_TEXT: 'ASSISTANT_TEXT',
  PURCHASE_ROBOT_CARD: 'PURCHASE_ROBOT_CARD', // 采购助手卡片
  PURCHASE_ROBOT_TEXT_CARD: 'PURCHASE_ROBOT_TEXT_CARD',
  PURCHASE_ROBOT_IMAGE_CARD: 'PURCHASE_ROBOT_IMAGE_CARD',
  PURCHASE_ROBOT_FILE_CARD: 'PURCHASE_ROBOT_FILE_CARD',
  PURCHASE_ROBOT_QUESTION_CARD: 'PURCHASE_ROBOT_QUESTION_CARD',
  PURCHASE_ROBOT_INQUIRY_FORM: 'PURCHASE_ROBOT_INQUIRY_FORM',
  PURCHASE_ROBOT_USER_EVAL_FORM: 'PURCHASE_ROBOT_USER_EVAL_FORM',
};

export const MSG_STATE = {
  RECEIVE: 0,
  RECALL: 1,
};

export const BUCKET_DIRECTORY = 'smbl-chatonline';
