// https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
module.exports = {
  'input-height-base': '32px',
  'btn-height-base': '32px',
  'font-size-base': '12px',
  'text-color': '#333',
  'float-label-color': 'rgb(0,0,0,0.65)',
  'float-label-font-size': '14px',
  'float-label-font-weight': '400',
  'border-radius-base': '2px',
  'primary-color': '#29BECE',
  'layout-header-height': '48px',
  'modal-mask-bg': 'rgba(0, 0, 0, 0.288)',
  'pagination-item-size': '26px',
  'form-item-margin-bottom': '14px',
  "hzero-primary-color-2-hover": "#4fd2db",
  'icon-url': `${process.env.PUBLIC_URL || '/'}assets/hzero-ui/font_148784_v4ggb6wrjmkotj4i`,
  // 'iconfont-css-prefix': 'c7n', // 设置 c7n 图标 class 前缀
  'disabled-color': 'rgba(0, 0, 0, 0.45)',
  'item-focus-bg': '#fff',
  'item-active-bg': '#f7f7f7',
  'table-row-hover-bg': '#f7f7f7',
  'table-current-row-bg': '#f0fffe',
  'table-padding-horizontal': '8px',
  'table-customization-form-padding-vertical': '12px',
  'input-required-bg': '#fffbef',
  'input-required-border-color': '#fca000',
  'input-hover-border-color': '#000',
  'input-disabled-color': '#000',
  'input-float-border-radius': '2px',
  'input-float-border-active-width': '1px',
  'input-float-required-border-color': '#fca000',
  'input-float-required-bg': '#fffbef',
  'input-float-error-bg': '#fcebeb',
  'input-tag-default-color': '#000',
  'input-tag-default-bg': '#ebebeb',
  'input-tag-close-color': 'rgba(0, 0, 0, 0.5)',
  'input-tag-close-hover-color': '#29BECE',
  'btn-padding-base': '0 15px',
  'btn-box-shadow': 'none',
  'btn-focus-box-shadow': 'none',
  'btn-active-box-shadow': 'none',
};