// 邀约信息所在页面
export const PAGE_TYPE = {
  INVITE_QUERY: 'inviteQuery',
  CERTIFICATION_DEAL: 'certificationDeal',
};

// 邀请注册单元编码
export const INVITE_REGISTER_CODE = [
  'SSLM.SUPPLIER_INVITE_MANAGE_LIST.REG_SUP_SAL_FORM',
  'SSLM.SUPPLIER_INVITE_MANAGE_LIST.REG_OFFER_INFO',
  'SSLM.SUPPLIER_INVITE_MANAGE_LIST.REG_INV_PUR',
  'SSLM.SUPPLIER_INVITE_MANAGE_LIST.REG_OTHERINFO',
];

// 邀请供应商单元编码
export const INVITE_SUPPLIER_CODE = [
  'SSLM.SUPPLIER_INVITE_MANAGE_LIST.SUP_SAL_FORM',
  'SSLM.SUPPLIER_INVITE_MANAGE_LIST.OFFER_INFORMATION',
  'SSLM.SUPPLIER_INVITE_MANAGE_LIST.INV_PUR_FORM',
  'SSLM.SUPPLIER_INVITE_MANAGE_LIST.OTHERINFO',
];
