// 查询条件配置 静态
import intl from 'utils/intl';
// import { SRM_DATA_SDAT } from '@/utils/config';
// import { getCurrentOrganizationId } from 'utils/utils';

// const tenantId = getCurrentOrganizationId();

export const getQueryConfig = () => {
  return {
    'SDAT.BANK_STATEMENT_INQUIRY.QUERY_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'pmtNum',
          fieldCode: 'pmtNum',
          fieldEditable: 1,
          fieldName: intl.get('sdat.bankStatementInquiry.model.pmtNum').d('SDAT支付平台单号'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 0,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          filterName: intl.get('hzero.common.view.title.default.filter').d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'tenantId',
              fieldCode: 'tenantId',
              fieldEditable: 1,
              fieldName: intl.get('sdat.customerAccount.model.tenantName').d('所属租户'),
              fieldVisible: 1,
              lovInfo: { displayField: 'tenantName', valueField: 'tenantId' },
              modelCode: 'tenantId',
              proDefaultFlag: 0,
              defaultValue: '',
              showFlag: 1,
              widget: {
                fieldWidget: 'LOV',
                linkNewWindow: 0,
                sourceCode: 'HPFM.TENANT',
                queryField: 'tenantName',
              },
              rank: 0,
              gridSeq: 0,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
            },
            // {
            //   customComparisonSet: ['LIKE'],
            //   fieldAlias: 'organizationCode',
            //   fieldCode: 'organizationCode',
            //   fieldEditable: 1,
            //   fieldName: intl.get('sdat.bankStatementInquiry.model.organizationCode').d('组织编码'),
            //   fieldVisible: 1,
            //   modelCode: 'organizationCode',
            //   proDefaultFlag: 0,
            //   showFlag: 1,
            //   widget: {
            //     fieldWidget: 'INPUT',
            //     linkNewWindow: 0,
            //   },
            //   gridSeq: 1,
            //   sortedFlag: 0,
            //   fixedFlag: 1,
            //   usedFlag: 1,
            //   rank: 1,
            // },
            {
              customComparisonSet: ['LIKE'],
              fieldAlias: 'pmtOutSerialNum',
              fieldCode: 'pmtOutSerialNum',
              fieldEditable: 1,
              fieldName: intl
                .get('sdat.bankStatementInquiry.model.bankSerialNumber')
                .d('第三方支付流水号'),
              fieldVisible: 1,
              modelCode: 'pmtOutSerialNum',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'INPUT',
                linkNewWindow: 0,
              },
              gridSeq: 2,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 1,
            },
            {
              customComparisonSet: ['LIKE'],
              fieldAlias: 'pmtOutBatchNum',
              fieldCode: 'pmtOutBatchNum',
              fieldEditable: 1,
              fieldName: intl
                .get('sdat.bankStatementInquiry.model.pmtOutBatchNum')
                .d('第三方系统支付批次号'),
              fieldVisible: 1,
              modelCode: 'pmtOutBatchNum',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'INPUT',
                linkNewWindow: 0,
              },
              gridSeq: 2,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 1,
            },
            {
              customComparisonSet: ['LIKE'],
              fieldAlias: 'pmtBizSerialNum',
              fieldCode: 'pmtBizSerialNum',
              fieldEditable: 1,
              fieldName: intl
                .get('sdat.bankStatementInquiry.model.pmtBizSerialNum')
                .d('支付业务流水号'),
              fieldVisible: 1,
              modelCode: 'pmtBizSerialNum',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'INPUT',
                linkNewWindow: 0,
              },
              gridSeq: 2,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 1,
            },
            {
              customComparisonSet: ['LIKE'],
              fieldAlias: 'pmtBizNum',
              fieldCode: 'pmtBizNum',
              fieldEditable: 1,
              fieldName: intl.get('sdat.bankStatementInquiry.model.pmtBizNum').d('支付业务单据号'),
              fieldVisible: 1,
              modelCode: 'pmtBizNum',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'INPUT',
                linkNewWindow: 0,
              },
              gridSeq: 2,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 1,
            },
            {
              customComparisonSet: ['LIKE'],
              fieldAlias: 'pmtSceneName',
              fieldCode: 'pmtSceneName',
              fieldEditable: 1,
              fieldName: intl
                .get('sdat.bankStatementInquiry.model.pmtSceneName')
                .d('支付业务场景名称'),
              fieldVisible: 1,
              modelCode: 'pmtSceneName',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'INPUT',
                linkNewWindow: 0,
              },
              gridSeq: 2,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 1,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'pmtTime',
              fieldCode: 'pmtTime',
              fieldEditable: 1,
              fieldName: intl.get('sdat.bankStatementInquiry.model.pmtStartTime').d('支付发起时间'),
              fieldVisible: 1,
              modelCode: 'pmtTime',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1,
              },
              rank: 0,
              gridSeq: 2,
              sortedFlag: 1,
              fixedFlag: 1,
              usedFlag: 1,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'pmtStatus',
              fieldCode: 'pmtStatus',
              fieldEditable: 1,
              fieldName: intl.get('sdat.bankStatementInquiry.model.pmtStatus').d('支付状态'),
              fieldVisible: 1,
              modelCode: 'pmtStatus',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                sourceCode: 'SDAT.BANK_PAY_STATUS',
              },
              gridSeq: 2,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 1,
            },
          ].filter(Boolean),
        },
      ],
    },
  };
};
