// 查询条件配置 静态
import intl from 'utils/intl';

export const getQueryConfig = () => {
  return {
    'SDAT.EVENT_COLLECT_MONITOR_SEARCH_BAR': {
      sortedEnabled: 1,
      mergeFieldList: [
        {
          fieldAlias: 'executeNumber',
          fieldCode: 'executeNumber',
          fieldEditable: 1,
          fieldName: intl
            .get('sdat.eventCollectMonitor.view.model.eventExecutionCode')
            .d('事件执行编码'),
          fieldVisible: 1,
          gridSeq: 0,
          showFlag: 0,
          sortedFlag: 0,
          customComparisonSet: ['LIKE'],
          widget: {
            fieldWidget: 'INPUT',
            linkNewWindow: 0,
            multipleFlag: 0,
          },
        },
      ],
      systemFilters: [
        {
          // defaultFlag: 1,
          // defaultSortedField: 'lastUpdateTime',
          // defaultSortedOrder: 'desc',
          filterName: intl
            .get('sdat.eventCollectMonitor.placeholder.defaultSelected')
            .d('默认筛选'),
          allFields: [
            {
              customComparisonSet: ['='],
              fieldAlias: 'riskType',
              fieldCode: 'riskType',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventCollectMonitor.view.model.riskType').d('风控类别'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'riskType',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.MONITOR_RISK_TYPE',
              },
              gridSeq: 1,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 1,
            },
            // {
            //   customComparisonSet: ['='],
            //   fieldAlias: 'executeType',
            //   fieldCode: 'executeType',
            //   fieldEditable: 1,
            //   fieldName: intl.get('sdat.eventCollectMonitor.view.model.eventType').d('事务类型'),
            //   fieldVisible: 1,
            //   lovInfo: { displayField: 'meaning', valueField: 'value' },
            //   modelCode: 'executeType',
            //   proDefaultFlag: 0,
            //   showFlag: 1,
            //   widget: {
            //     fieldWidget: 'SELECT',
            //     linkNewWindow: 0,
            //     lovInfo: { displayField: 'meaning', valueField: 'value' },
            //     sourceCode: 'SDAT.EVENT_MONITOR_TYPE',
            //   },
            //   gridSeq: 2,
            //   sortedFlag: 0,
            //   fixedFlag: 1,
            //   usedFlag: 1,
            //   rank: 2,
            // },
            {
              customComparisonSet: ['='],
              fieldAlias: 'tenantId',
              fieldCode: 'tenantId',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventCollectMonitor.view.model.tenantName').d('租户'),
              fieldVisible: 1,
              lovInfo: { displayField: 'tenantName', valueField: 'tenantId' },
              modelCode: 'tenantId',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'LOV',
                linkNewWindow: 0,
                sourceCode: 'SDAT.MONITOR_TENANT',
              },
              gridSeq: 3,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 3,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'strikeType',
              fieldCode: 'strikeType',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventCollectMonitor.view.model.triggerType').d('触发类型'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'strikeType',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'SDAT.MONITOR_STRIKE_TYPE',
              },
              gridSeq: 6,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
              rank: 6,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'monitorDate',
              fieldCode: 'monitorDate',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventCollectMonitor.view.model.monitorDate').d('监控日期'),
              fieldVisible: 1,
              modelCode: 'monitorDate',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1, // 是否是range
              },
              rank: 3,
              gridSeq: 3,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
            },
            {
              customComparisonSet: ['IN'],
              fieldAlias: 'dateProd',
              fieldCode: 'dateProd',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventCollectMonitor.view.model.dateProd').d('执行时间范围'),
              fieldVisible: 1,
              modelCode: 'dateProd',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                dateFormat: 'YYYY-MM-DD',
                fieldWidget: 'DATE_PICKER',
                linkNewWindow: 0,
                multipleFlag: 1, // 是否是range
              },
              rank: 4,
              gridSeq: 4,
              sortedFlag: 0,
              fixedFlag: 1,
              usedFlag: 1,
            },
            {
              customComparisonSet: ['='],
              fieldAlias: 'executeStatus',
              fieldCode: 'executeStatus',
              fieldEditable: 1,
              fieldName: intl.get('sdat.eventCollectMonitor.view.model.execuSuccess').d('执行成功'),
              fieldVisible: 1,
              lovInfo: { displayField: 'meaning', valueField: 'value' },
              modelCode: 'executeStatus',
              proDefaultFlag: 0,
              showFlag: 1,
              widget: {
                fieldWidget: 'SELECT',
                linkNewWindow: 0,
                lovInfo: { displayField: 'meaning', valueField: 'value' },
                sourceCode: 'HPFM.FLAG',
              },
              gridSeq: 7,
              sortedFlag: 0,
              fixedFlag: 0,
              usedFlag: 0,
              rank: 7,
            },
          ].filter(Boolean),
        },
      ],
    },
  };
};
