declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'
declare module "*.less"
declare module "*.css"
declare module "utils/remote"
declare module "_components/AFCards"
declare module "_components/ApproveModal"
declare module "_components/FilterBarTable"
declare module "_components/PrintProButton"
declare module "_components/ApproveRecordSimple"
declare module "hzero-front/lib/utils/remote"
interface Window {
  [x: string]: any;
}