// https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
let publicUrl = process.env.PUBLIC_URL || '';
publicUrl = publicUrl.endsWith('/') ? publicUrl : ''.concat(publicUrl, '/');
module.exports = {
  // basic
  'primary-color': '#29BECE',
  'hzero-primary-color-2-hover': '#4fd2db',
  'text-color': '#000',
  'disabled-color': 'rgba(0, 0, 0, 0.45)',
  'font-family': '12px',
  'font-size-base': '12px',
  'border-radius-base': '2px',
  'icon-url': ''.concat(publicUrl, 'assets/hzero-ui/font_148784_v4ggb6wrjmkotj4i'),
  // 'iconfont-css-prefix': 'c7n', // 设置 c7n 图标 class 前缀
  'item-focus-bg': '#fff',
  'item-active-bg': '#f7f7f7',
  // colors
  'red-1': 'fade(#F56349, 10%)',
  'red-3': 'fade(#F56349, 15%)',
  'red-6': '#F56349',
  'green-1': 'fade(#47B881, 10%)',
  'green-3': 'fade(#47B881, 15%)',
  'green-6': '#47B881',
  'yellow-1': 'fade(#F88D10, 10%)',
  'yellow-3': 'fade(#F88D10, 15%)',
  'yellow-6': '#F88D10',
  'cyan-1': 'fade(#36C2CF, 10%)',
  'cyan-3': 'fade(#36C2CF, 15%)',
  'cyan-6': '#36C2CF',
  'blue-1': 'fade(#3095F2, 10%)',
  'blue-3': 'fade(#3095F2, 15%)',
  'blue-6': '#3095F2',
  'purple-1': 'fade(#3F5BB5, 10%)',
  'purple-3': 'fade(#3F5BB5, 15%)',
  'purple-6': '#3F5BB5',
  'gray-1': 'fade(#000, 10%)',
  'gray-3': 'fade(#000, 15%)',
  'gray-6': 'fade(#000, 65%)',
  // form field
  'label-color-vertical': 'rgba(0, 0, 0, 0.5)',
  'label-white-space': 'normal',
  'label-wrapper-padding-horizontal': '0',
  'label-output-wrapper-padding-vertical': '0.1rem',
  'label-vertical-wrapper-padding-vertical': '0.05rem',
  'form-item-wrapper-padding-horizontal': '0',
  'form-item-wrapper-output-padding-vertical': '0.1rem',
  'form-item-margin-bottom': '18px',
  'float-label-height-base': '32px',
  'float-label-height-lg': '36px',
  'float-label-height-sm': '28px',
  'float-label-autofill-margin': '2px',
  'float-label-line-height': '30px',
  'float-label-line-height-lg': '34px',
  'float-label-line-height-sm': '26px',
  'float-label-color': 'rgba(0, 0, 0, 0.5)',
  'float-label-font-size': '14px',
  'float-label-font-weight': '400',
  // input
  'input-height-base': '32px',
  'input-height-lg': '36px',
  'input-height-sm': '28px',
  'input-padding-horizontal': '10px',
  'input-required-bg': '#fffbef',
  'input-required-border-color': '#fca000',
  'input-required-hover-border-color': '#ec9600',
  'input-hover-border-color': '#000',
  'input-disabled-color': '#000',
  'input-float-border-radius': '2px',
  'input-float-border-active-width': '1px',
  'input-float-required-border-color': '#fca000',
  'input-float-required-hover-border-color': '#ec9600',
  'input-float-required-bg': '#fffbef',
  'input-float-error-bg': '#fcebeb',
  'input-tag-default-color': '#000',
  'input-tag-default-bg': '#ebebeb',
  'input-tag-close-color': 'rgba(0, 0, 0, 0.5)',
  'input-tag-close-hover-color': '#29BECE',
  // output
  'output-line-height': '2.5',
  'output-font-weight': '500',
  'output-white-space': 'pre-wrap',
  // 'output-word-break': 'break-word',
  // radio
  'radio-label-white-space': 'nowrap',
  // btn
  'btn-height-base': '32px',
  'btn-padding-base': '0 15px',
  'btn-box-shadow': 'none',
  'btn-focus-box-shadow': 'none',
  'btn-active-box-shadow': 'none',
  'btn-group-spacing': '0.08rem',
  'btn-primary-bg': '#29BECE',
  'btn-primary-focus-bg': '#4fd2db',
  'btn-font-weight': '600',
  'btn-link-font-weight': '400',
  'btn-icon-font-weight': '400',
  'btn-raised-border-width-base': '1px',
  'btn-default-border': 'rgba(0, 0, 0, 0.2)',
  // table
  'table-header-font-weight': '600',
  'table-border-color': '#EBEBEB',
  'table-row-hover-bg': '#F5F5F5',
  'table-current-row-bg': '#EBEBEB',
  'table-even-row-bg': '#F5F5F5',
  'table-padding-horizontal': '8px',
  'table-customization-form-padding-vertical': '12px',
  'table-cell-padding-vertical-base': '5px',
  'table-cell-padding-horizontal-base': '10px',
  'table-cell-padding-vertical-sm': '2px',
  'table-cell-padding-horizontal-sm': '10px',
  'table-editable-cell-border-radius-base': '2px',
  'table-editable-cell-disabled-bg': '#f5f5f5',
  'table-editable-cell-disabled-border-color': 'rgba(0, 0, 0, 0.2)',
  'table-icon-help-color': 'rgba(0, 0, 0, 0.5)',
  'table-icon-help-size': '14px',
  'table-icon-help-content': '"\\E887"',
  'table-icon-help-font-weight': '400',
  // modal
  'modal-title-color': '#000',
  'modal-title-font-size-base': '16px',
  'modal-confirm-title-font-size-base': '16px',
  'modal-title-font-weight': '700',
  'modal-mask-bg': 'rgba(0, 0, 0, 0.288)',
  'modal-drawer-header-padding': '15px 20px',
  'modal-drawer-body-padding': '20px',
  'modal-drawer-footer-padding': '12px 20px',
  // switch
  'switch-wrapper-padding': '0',
  'switch-padding-horizontal': '2px',
  'switch-min-width': '44px',
  'switch-height': '22px',
  'switch-line-height': '20px',
  'switch-button-size': '18px',
  'switch-button-active-width': '22px',
  'switch-sm-min-width': '38px',
  'switch-sm-height': '18px',
  'switch-sm-line-height': '16px',
  'switch-sm-button-size': '14px',
  'switch-sm-button-active-width': '18px',
  'switch-lg-min-width': '48px',
  'switch-lg-height': '26px',
  'switch-lg-line-height': '24px',
  'switch-lg-button-size': '22px',
  'switch-lg-button-active-width': '26px',
  'switch-bg': 'rgba(0, 0, 0, 0.25)',
  'switch-button-bg': '#fff',
  'switch-checked-bg': '#36c2cf',
  'switch-checked-button-bg': '#fff',
  // tab
  'tabs-title-font-size': '14px',
  'tab-horizontal-padding': '0 0 12px 0',
  'tabs-groups-ink-bar-display': 'none',
  'tab-groups-bar-padding': '0 0 12px 0',
  'tab-groups-horizontal-padding': '0',
  // tag
  'tag-font-weight': '600',
  // alert
  'alert-icon-top': '8px',
  // icon
  'icon-font-family': 'c7nIcon',
  // other
  'pagination-item-size': '26px',
  'layout-header-height': '48px',
  'lov-selection-list-bg': '#fbfbfc',
};
