export const protocalUnitCode = {
  history: 'SMAL.AGREEMENT_MANAGEMENT.HISTORY_FORM',
  edit: 'SMAL.AGREEMENT_MANAGEMENT.PROTOCAL_FORM',
  view: 'SMAL.AGREEMENT_MANAGEMENT.PROTOCAL_ONLYREAD',
};

export const protocalDetailCode = {
  LIST: 'SMAL.AGREEMENT_MANAGEMENT.DETAIL',
  SEARCH_FORM: 'SMAL.AGREEMENT_MANAGEMENT.DETAILSEARCH',
};

export const batchProtocalCode = {
  BATCH_PRICE_FORM: 'SMAL.AGREEMENT_MANAGEMENT.IMOIRT_PRICE_LIB_NEW_FORM',
  BATCH_MANUAL_FORM: 'SMAL.AGREEMENT_MANAGEMENT.IMPORT_MANUAL_NEW_FORM1',
};

// 工作台
export const workBenchFormUnitCode = {
  history: 'SAGM.WORKBENCH.MAIN.HISTORY.FORM',
  edit: 'SAGM.WORKBENCH.MAIN.PROTOCOL.FORM',
  view: 'SAGM.WORKBENCH.MAIN.PROTOCOL.ONLY_READ',
  attachment: 'SAGM.WORKBENCH.MAIN.ATTACHMENT',
  manual_line: 'SAGM.WORKBENCH.MAIN.LINE.MANUAL_NEW', // 手工新建协议行
  lib_line: 'SAGM.WORKBENCH.MAIN.LINE.PRICE_LIB_NEW', // 价格库新建协议行
  line_btns: 'SAGM.WORKBENCH.LINE.TABLE.BTNS', // 协议行头按钮
};
